- name: First interaction
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Hello @${{ github.actor }} , It's great having you contribute to this project. Welcome to the community :nerd:face'
          pr-message: 'Hello @${{ github.actor }} , thank you submitting a pull request!'
